// Code generated by Slice Machine. DO NOT EDIT.

import BmiCalculator from './BmiCalculator';
import Counter from './Counter';
import Cta from './Cta';
import Gallery from './Gallery';
import Hero from './Hero';
import ImageCards from './ImageCards';
import PricingPackages from './PricingPackages';
import Quote from './Quote';
import Reviews from './Reviews';
import Text from './Text';
import TextWithImage from './TextWithImage';

export {
  BmiCalculator,
  Counter,
  Cta,
  Gallery,
  Hero,
  ImageCards,
  PricingPackages,
  Quote,
  Reviews,
  Text,
  TextWithImage,
};

export const components = {
  bmi_calculator: BmiCalculator,
  counter: Counter,
  cta: Cta,
  gallery: Gallery,
  hero: Hero,
  image_cards: ImageCards,
  pricing_packages: PricingPackages,
  quote: Quote,
  reviews: Reviews,
  text: Text,
  text_with_image: TextWithImage,
};
